export { default as Hero } from "./Hero.jsx";
export { default as Sales } from "./Sales.jsx";
export { default as Highlights } from "./Highlights.jsx";
export { default as News } from "./News.jsx";
export { default as Footer } from "./Footer.jsx";
export { default as NavBar } from "./NavBar.jsx";
export { default as Cart } from "./Cart.jsx";
export { default as Favourites } from "./Favourites.jsx";
export { default as FavItem } from "./FavItem.jsx";
